In [1]:
import json
import pandas as pd
from collections import Counter
from pprint import pprint

DATA_FILE = "/Users/ishitabelwal/Downloads/firmable_2M.jsonl"

In [2]:
with open(DATA_FILE, "r", encoding="utf-8") as f:
    first_record = json.loads(f.readline())

pprint(first_record)

{'_shodan': {'crawler': '85a2598833c03b2cff4b6d747001845f87a89147',
             'id': '90cc99c7-b355-4b90-871a-a779a94b8565',
             'module': 'auto',
             'options': {},
             'region': 'na'},
 'asn': 'AS54994',
 'cpe': ['cpe:/a:f5:nginx'],
 'cpe23': ['cpe:2.3:a:f5:nginx'],
 'cpe23_hash': -1725627573,
 'data': 'HTTP/1.1 400 Bad Request\r\n'
         'Server: nginx\r\n'
         'Date: Mon, 14 Sep 2026 09:59:26 GMT\r\n'
         'Content-Type: text/html\r\n'
         'Content-Length: 2407\r\n'
         'Connection: close\r\n'
         'x-ws-request-id: 6aa7c57e_PS-000-04n1F132_35640-46324\r\n'
         '\r\n',
 'domains': [],
 'hash': 867632950,
 'hostnames': [],
 'http': {'components': {'Nginx': {'categories': ['Web servers',
                                                  'Reverse proxies']}},
          'components_hash': 1840820445,
          'dom_hash': -609433485,
          'headers': {'connection': 'close',
                      'content-length': '2407',
                      'content-type': 'text/html',
                      'date': 'Mon, 14 Sep 2026 09:59:26 GMT',
                      'server': 'nginx',
                      'x-ws-request-id': '6aa7c57e_PS-000-04n1F132_35640-46324'},
          'headers_hash': 1280049706,
          'host': '138.113.61.106',
          'html': '<!DOCTYPE html>\n'
                  '<html>\n'
                  '\t<head>\n'
                  '\t\t<meta charset="utf-8">\n'
                  '\t\t<meta http-equiv="X-UA-Compatible" content="IE=edge">\n'
                  '\t\t<meta name="viewport" content="width=device-width, '
                  'initial-scale=1">\n'
                  '\t\t<title>400 Bad Request</title>\n'
                  '\t\t<style type="text/css">body{margin:5% auto 0 '
                  'auto;padding:0 18px}.P{margin:0 '
                  '22%}.O{margin-top:20px}.N{margin-top:10px}.M{margin:10px 0 '
                  '30px '
                  '0}.L{margin-bottom:60px}.K{font-size:25px;color:#F90}.J{font-size:14px}.I{font-size:20px}.H{font-size:18px}.G{font-size:16px}.F{width:230px;float:left}.E{margin-top:5px}.D{margin:8px '
                  '0 0 '
                  '-20px}.C{color:#3CF;cursor:pointer}.B{color:#909090;margin-top:15px}.A{line-height:30px}.hide_me{display:none}</style>\n'
                  '\t</head>\n'
                  '\t<body>\n'
                  '\t\t<div id="p" class="P">\n'
                  '\t\t\t<div class="K">400</div>\n'
                  '\t\t\t<div class="O I">Bad Request</div>\n'
                  '\t\t\t<p class="J A L">Error Times: Mon, 14 Sep 2026 '
                  '09:59:26 GMT\n'
                  '\t\t\t\t<br>\n'
                  '\t\t\t\t<span class="F">IP: 224.67.70.229</span>Node '
                  'information: PS-000-04n1F132\n'
                  '\t\t\t\t<br>URL: http://138.113.61.106/\n'
                  '\t\t\t\t<br>Request-Id: '
                  '6aa7c57e_PS-000-04n1F132_35640-46324\n'
                  '\t\t\t\t<br>Check:\n'
                  '\t\t\t\t<span class="C G" '
                  'onclick="s(0)">Details</span></p>\n'
                  '\t\t</div>\n'
                  '\t\t<div id="d" class="hide_me P H">\n'
                  '\t\t\t<div class="K">ERROR</div>\n'
                  '\t\t\t<p class="O I">"The Requested URL could not be '
                  'retrieved</p>\n'
                  '\t\t\t<div class="O">\n'
                  '\t\t\t\t<div>While trying to retrieve the URL:</div>\n'
                  '\t\t\t\t<pre class="B '
                  'G">http://138.113.61.106/</pre></div>\n'
                  '\t\t\t<div class="M">\n'
                  '\t\t\t\t<span>The following error was encountered:</span>\n'
                  '\t\t\t\t<ul class="E">\n'
                  '\t\t\t\t\t<li class="D G">Invalid Request</li></ul>\n'
                  '\t\t\t</div>\n'
                  '\t\t\t<div class="M">\n'
                  '\t\t\t\t<span>This request could not be forwarded to the '
                  'origin server or to any higher level cache servers. The '
                  'most likely cause for this error is that:</span>\n'
                  '\t\t\t\t<ul class="E G">\n'
                  '\t\t\t\t\t<li class="D">Missing or unknown request '
                  'method</li>\n'
                  '\t\t\t\t\t<li class="D">Missing URL</li>\n'
                  '\t\t\t\t\t<li class="D">Missing HTTP Identifier '
                  '(HTTP/1.0)</li>\n'
                  '\t\t\t\t\t<li class="D">Request is too large</li>\n'
                  '\t\t\t\t\t<li class="D">Content-Length missing for POST or '
                  'PUT requests</li>\n'
                  '\t\t\t\t\t<li class="D">Illegal character in '
                  'hostname;underscores are not allowed</li>\n'
                  '\t\t\t\t\t<li class="D">Range Invalid</li></ul>\n'
                  '\t\t\t</div>\n'
                  '\t\t\t<a class="N C" href="#" '
                  'onclick="s(1)">return</a></div>\n'
                  '\t\t<script type="text/javascript">function e(i) {\n'
                  '\t\t\t\treturn document.getElementById(i);\n'
                  '\t\t\t}\n'
                  '\t\t\tfunction d(i, t) {\n'
                  "\t\t\t\te(i).style.display = (t ? 'block': 'none');\n"
                  '\t\t\t}\n'
                  '\t\t\tfunction s(e) {\n'
                  "\t\t\t\td('p', e);\n"
                  "\t\t\t\td('d', !e);\n"
                  '\t\t\t}</script>\n'
                  '\t</body>\n'
                  '</html>',
          'html_hash': 1742693465,
          'location': '/',
          'redirects': [],
          'robots': None,
          'robots_hash': None,
          'securitytxt': None,
          'securitytxt_hash': None,
          'server': 'nginx',
          'server_hash': -1340961475,
          'sitemap': None,
          'sitemap_hash': None,
          'status': 400,
          'title': '400 Bad Request',
          'title_hash': -674769028},
 'ip': 2322677098,
 'ip_str': '138.113.61.106',
 'isp': 'Meteverse Limited.',
 'location': {'area_code': None,
              'city': 'Tseung Kwan O',
              'country_code': 'HK',
              'country_name': 'Hong Kong',
              'latitude': 22.32789,
              'longitude': 114.24992,
              'region_code': ''},
 'opts': {},
 'org': 'Meteverse Limited.',
 'os': None,
 'port': 15123,
 'product': 'nginx',
 'timestamp': '2026-09-14T09:59:27.083391',
 'transport': 'tcp'}

In [3]:
print(first_record.keys())

dict_keys(['data', 'opts', 'port', 'hostnames', 'timestamp', 'domains', 'location', 'org', 'isp', 'os', 'product', 'http', 'ip', 'cpe23', 'cpe', '_shodan', 'cpe23_hash', 'hash', 'transport', 'ip_str', 'asn'])

In [4]:
for key, value in first_record.items():
    print(f"{key:15} -> {type(value).__name__}")

data            -> str
opts            -> dict
port            -> int
hostnames       -> list
timestamp       -> str
domains         -> list
location        -> dict
org             -> str
isp             -> str
os              -> NoneType
product         -> str
http            -> dict
ip              -> int
cpe23           -> list
cpe             -> list
_shodan         -> dict
cpe23_hash      -> int
hash            -> int
transport       -> str
ip_str          -> str
asn             -> str

In [7]:
from pprint import pprint

print("========== LOCATION ==========")
pprint(first_record["location"])

print("\n========== HTTP ==========")
pprint(first_record["http"])

print("\n========== OPTS ==========")
pprint(first_record["opts"])

print("\n========== CPE23 ==========")
pprint(first_record["cpe23"])

print("\n========== CPE ==========")
pprint(first_record["cpe"])

print("\n========== SHODAN ==========")
pprint(first_record["_shodan"])

========== LOCATION ==========
{'area_code': None,
 'city': 'Tseung Kwan O',
 'country_code': 'HK',
 'country_name': 'Hong Kong',
 'latitude': 22.32789,
 'longitude': 114.24992,
 'region_code': ''}

========== HTTP ==========
{'components': {'Nginx': {'categories': ['Web servers', 'Reverse proxies']}},
 'components_hash': 1840820445,
 'dom_hash': -609433485,
 'headers': {'connection': 'close',
             'content-length': '2407',
             'content-type': 'text/html',
             'date': 'Mon, 14 Sep 2026 09:59:26 GMT',
             'server': 'nginx',
             'x-ws-request-id': '6aa7c57e_PS-000-04n1F132_35640-46324'},
 'headers_hash': 1280049706,
 'host': '138.113.61.106',
 'html': '<!DOCTYPE html>\n'
         '<html>\n'
         '\t<head>\n'
         '\t\t<meta charset="utf-8">\n'
         '\t\t<meta http-equiv="X-UA-Compatible" content="IE=edge">\n'
         '\t\t<meta name="viewport" content="width=device-width, '
         'initial-scale=1">\n'
         '\t\t<title>400 Bad Request</title>\n'
         '\t\t<style type="text/css">body{margin:5% auto 0 auto;padding:0 '
         '18px}.P{margin:0 '
         '22%}.O{margin-top:20px}.N{margin-top:10px}.M{margin:10px 0 30px '
         '0}.L{margin-bottom:60px}.K{font-size:25px;color:#F90}.J{font-size:14px}.I{font-size:20px}.H{font-size:18px}.G{font-size:16px}.F{width:230px;float:left}.E{margin-top:5px}.D{margin:8px '
         '0 0 '
         '-20px}.C{color:#3CF;cursor:pointer}.B{color:#909090;margin-top:15px}.A{line-height:30px}.hide_me{display:none}</style>\n'
         '\t</head>\n'
         '\t<body>\n'
         '\t\t<div id="p" class="P">\n'
         '\t\t\t<div class="K">400</div>\n'
         '\t\t\t<div class="O I">Bad Request</div>\n'
         '\t\t\t<p class="J A L">Error Times: Mon, 14 Sep 2026 09:59:26 GMT\n'
         '\t\t\t\t<br>\n'
         '\t\t\t\t<span class="F">IP: 224.67.70.229</span>Node information: '
         'PS-000-04n1F132\n'
         '\t\t\t\t<br>URL: http://138.113.61.106/\n'
         '\t\t\t\t<br>Request-Id: 6aa7c57e_PS-000-04n1F132_35640-46324\n'
         '\t\t\t\t<br>Check:\n'
         '\t\t\t\t<span class="C G" onclick="s(0)">Details</span></p>\n'
         '\t\t</div>\n'
         '\t\t<div id="d" class="hide_me P H">\n'
         '\t\t\t<div class="K">ERROR</div>\n'
         '\t\t\t<p class="O I">"The Requested URL could not be retrieved</p>\n'
         '\t\t\t<div class="O">\n'
         '\t\t\t\t<div>While trying to retrieve the URL:</div>\n'
         '\t\t\t\t<pre class="B G">http://138.113.61.106/</pre></div>\n'
         '\t\t\t<div class="M">\n'
         '\t\t\t\t<span>The following error was encountered:</span>\n'
         '\t\t\t\t<ul class="E">\n'
         '\t\t\t\t\t<li class="D G">Invalid Request</li></ul>\n'
         '\t\t\t</div>\n'
         '\t\t\t<div class="M">\n'
         '\t\t\t\t<span>This request could not be forwarded to the origin '
         'server or to any higher level cache servers. The most likely cause '
         'for this error is that:</span>\n'
         '\t\t\t\t<ul class="E G">\n'
         '\t\t\t\t\t<li class="D">Missing or unknown request method</li>\n'
         '\t\t\t\t\t<li class="D">Missing URL</li>\n'
         '\t\t\t\t\t<li class="D">Missing HTTP Identifier (HTTP/1.0)</li>\n'
         '\t\t\t\t\t<li class="D">Request is too large</li>\n'
         '\t\t\t\t\t<li class="D">Content-Length missing for POST or PUT '
         'requests</li>\n'
         '\t\t\t\t\t<li class="D">Illegal character in hostname;underscores '
         'are not allowed</li>\n'
         '\t\t\t\t\t<li class="D">Range Invalid</li></ul>\n'
         '\t\t\t</div>\n'
         '\t\t\t<a class="N C" href="#" onclick="s(1)">return</a></div>\n'
         '\t\t<script type="text/javascript">function e(i) {\n'
         '\t\t\t\treturn document.getElementById(i);\n'
         '\t\t\t}\n'
         '\t\t\tfunction d(i, t) {\n'
         "\t\t\t\te(i).style.display = (t ? 'block': 'none');\n"
         '\t\t\t}\n'
         '\t\t\tfunction s(e) {\n'
         "\t\t\t\td('p', e);\n"
         "\t\t\t\td('d', !e);\n"
         '\t\t\t}</script>\n'
         '\t</body>\n'
         '</html>',
 'html_hash': 1742693465,
 'location': '/',
 'redirects': [],
 'robots': None,
 'robots_hash': None,
 'securitytxt': None,
 'securitytxt_hash': None,
 'server': 'nginx',
 'server_hash': -1340961475,
 'sitemap': None,
 'sitemap_hash': None,
 'status': 400,
 'title': '400 Bad Request',
 'title_hash': -674769028}

========== OPTS ==========
{}

========== CPE23 ==========
['cpe:2.3:a:f5:nginx']

========== CPE ==========
['cpe:/a:f5:nginx']

========== SHODAN ==========
{'crawler': '85a2598833c03b2cff4b6d747001845f87a89147',
 'id': '90cc99c7-b355-4b90-871a-a779a94b8565',
 'module': 'auto',
 'options': {},
 'region': 'na'}

In [8]:
print(first_record["data"])

HTTP/1.1 400 Bad Request
Server: nginx
Date: Mon, 14 Sep 2026 09:59:26 GMT
Content-Type: text/html
Content-Length: 2407
Connection: close
x-ws-request-id: 6aa7c57e_PS-000-04n1F132_35640-46324

In [9]:
list_fields = [
    "hostnames",
    "domains",
    "cpe23",
    "cpe"
]

for field in list_fields:
    value = first_record.get(field)
    print(f"{field:12} -> {len(value)} items")

hostnames    -> 0 items
domains      -> 0 items
cpe23        -> 1 items
cpe          -> 1 items

In [10]:
print("Organization :", first_record.get("org"))
print("ISP          :", first_record.get("isp"))
print("ASN          :", first_record.get("asn"))
print("IP           :", first_record.get("ip_str"))
print("Port         :", first_record.get("port"))
print("Transport    :", first_record.get("transport"))
print("Product      :", first_record.get("product"))
print("OS           :", first_record.get("os"))
print("Timestamp    :", first_record.get("timestamp"))

Organization : Meteverse Limited.
ISP          : Meteverse Limited.
ASN          : AS54994
IP           : 138.113.61.106
Port         : 15123
Transport    : tcp
Product      : nginx
OS           : None
Timestamp    : 2026-09-14T09:59:27.083391

In [12]:
import os

print(os.getcwd())

/Users/ishitabelwal/Documents/cybersignal/notebooks

In [13]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

/Users/ishitabelwal/Documents/cybersignal

In [14]:
# testing out normalizer
from src.ingestion.normalize import normalize_record

normalized = normalize_record(first_record)
pprint(normalized)

{'asn': 'AS54994',
 'city': 'Tseung Kwan O',
 'country_code': 'HK',
 'country_name': 'Hong Kong',
 'cpe': ['cpe:/a:f5:nginx'],
 'cpe23': ['cpe:2.3:a:f5:nginx'],
 'domains': [],
 'hostnames': [],
 'http_components': {'Nginx': {'categories': ['Web servers',
                                              'Reverse proxies']}},
 'http_host': '138.113.61.106',
 'http_server': 'nginx',
 'http_status': 400,
 'http_title': '400 Bad Request',
 'ip': '138.113.61.106',
 'isp': 'Meteverse Limited.',
 'organization': 'Meteverse Limited.',
 'os': None,
 'port': 15123,
 'product': 'nginx',
 'timestamp': '2026-09-14T09:59:27.083391',
 'transport': 'tcp'}

In [15]:
test_records = []

with open(DATA_FILE, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if i >= 100:
            break

        test_records.append(json.loads(line))

print(f"Loaded {len(test_records)} records")

Loaded 100 records

In [16]:
normalized_records = []

for record in test_records:
    normalized_records.append(
        normalize_record(record)
    )

print(f"Normalized {len(normalized_records)} records")

Normalized 100 records

In [17]:
test_df = pd.DataFrame(normalized_records)

test_df.head()

,organization,isp,asn,ip,port,transport,product,os,country_code,country_name,...,domains,hostnames,cpe,cpe23,http_status,http_server,http_title,http_host,http_components,timestamp
0,Meteverse Limited.,Meteverse Limited.,AS54994,138.113.61.106,15123,tcp,nginx,NaN,HK,Hong Kong,...,[],[],[cpe:/a:f5:nginx],[cpe:2.3:a:f5:nginx],400.0,nginx,400 Bad Request,138.113.61.106,"{'Nginx': {'categories': ['Web servers', 'Reve...",2026-09-14T09:59:27.083391
1,Korea Telecom,Korea Telecom,AS4766,218.150.120.133,8008,tcp,Chromecast,NaN,KR,"Korea, Republic of",...,[],[],[],[],403.0,NaN,NaN,218.150.120.133,{},2026-09-14T09:59:56.544376
2,Google LLC,NaN,NaN,136.79.64.193,53,tcp,NaN,NaN,US,United States,...,[googleusercontent.com],[193.64.79.136.bc.googleusercontent.com],[],[],NaN,NaN,NaN,NaN,{},2026-09-14T09:59:58.072744
3,"Fly.io, Inc.","Fly.io, Inc.",AS40509,137.66.8.132,12304,tcp,NaN,NaN,GB,United Kingdom,...,[flyio.net],[ip-137-66-8-132.customer.flyio.net],[],[],NaN,NaN,NaN,NaN,{},2026-09-14T09:59:57.821438
4,Google LLC,"Level 3 Parent, LLC",AS3356,8.233.15.235,7171,tcp,NaN,NaN,US,United States,...,[googleusercontent.com],[235.15.233.8.bc.googleusercontent.com],[],[],NaN,NaN,NaN,NaN,{},2026-09-14T09:59:57.212703

In [18]:
test_df.shape

(100, 21)

In [19]:
test_df.columns.tolist()

['organization',
 'isp',
 'asn',
 'ip',
 'port',
 'transport',
 'product',
 'os',
 'country_code',
 'country_name',
 'city',
 'domains',
 'hostnames',
 'cpe',
 'cpe23',
 'http_status',
 'http_server',
 'http_title',
 'http_host',
 'http_components',
 'timestamp']

In [20]:
test_df.isna().sum()

organization        0
isp                12
asn                12
ip                  2
port                0
transport           0
product            82
os                 99
country_code        0
country_name        0
city                0
domains             0
hostnames           0
cpe                 0
cpe23               0
http_status        68
http_server        76
http_title         80
http_host          68
http_components     0
timestamp           0
dtype: int64

In [21]:
test_df.dtypes

organization           str
isp                    str
asn                    str
ip                     str
port                 int64
transport              str
product                str
os                     str
country_code           str
country_name           str
city                   str
domains             object
hostnames           object
cpe                 object
cpe23               object
http_status        float64
http_server            str
http_title             str
http_host              str
http_components     object
timestamp              str
dtype: object

In [22]:
errors = []

for i, record in enumerate(test_records):
    try:
        normalize_record(record)
    except Exception as e:
        errors.append({
            "record_number": i,
            "error": str(e)
        })

print(f"Errors: {len(errors)}")

Errors: 0

In [23]:
from src.ingestion.jsonl_reader import read_jsonl

In [24]:
for line_number, record in read_jsonl(DATA_FILE):

    print("Line:", line_number)
    print("Organization:", record.get("org"))
    print("Product:", record.get("product"))

    break

Line: 1
Organization: Meteverse Limited.
Product: nginx

In [25]:
count = 0

for line_number, record in read_jsonl(DATA_FILE):

    count += 1

    if count <= 5:
        print(
            line_number,
            record.get("org"),
            record.get("product")
        )

    if count == 100:
        break

print("Records read:", count)

1 Meteverse Limited. nginx
2 Korea Telecom Chromecast
3 Google LLC None
4 Fly.io, Inc. None
5 Google LLC None
Records read: 100

In [26]:
import duckdb

con = duckdb.connect()

In [29]:
df = con.execute("""
    SELECT *
    FROM '../data/processed/observations_test/*.parquet'
    LIMIT 10
""").df()

df

,organization,isp,asn,ip,port,transport,product,os,country_code,country_name,...,domains,hostnames,cpe,cpe23,http_status,http_server,http_title,http_host,http_components,timestamp
0,Meteverse Limited.,Meteverse Limited.,AS54994,138.113.61.106,15123,tcp,nginx,None,HK,Hong Kong,...,[],[],[cpe:/a:f5:nginx],[cpe:2.3:a:f5:nginx],400.0,nginx,400 Bad Request,138.113.61.106,"{'Nginx': {'categories': ['Web servers', 'Reve...",2026-09-14T09:59:27.083391
1,Korea Telecom,Korea Telecom,AS4766,218.150.120.133,8008,tcp,Chromecast,None,KR,"Korea, Republic of",...,[],[],[],[],403.0,NaN,NaN,218.150.120.133,"{'Nginx': None, 'jQuery': None, 'jQuery UI': N...",2026-09-14T09:59:56.544376
2,Google LLC,NaN,NaN,136.79.64.193,53,tcp,NaN,None,US,United States,...,[googleusercontent.com],[193.64.79.136.bc.googleusercontent.com],[],[],NaN,NaN,NaN,NaN,"{'Nginx': None, 'jQuery': None, 'jQuery UI': N...",2026-09-14T09:59:58.072744
3,"Fly.io, Inc.","Fly.io, Inc.",AS40509,137.66.8.132,12304,tcp,NaN,None,GB,United Kingdom,...,[flyio.net],[ip-137-66-8-132.customer.flyio.net],[],[],NaN,NaN,NaN,NaN,"{'Nginx': None, 'jQuery': None, 'jQuery UI': N...",2026-09-14T09:59:57.821438
4,Google LLC,"Level 3 Parent, LLC",AS3356,8.233.15.235,7171,tcp,NaN,None,US,United States,...,[googleusercontent.com],[235.15.233.8.bc.googleusercontent.com],[],[],NaN,NaN,NaN,NaN,"{'Nginx': None, 'jQuery': None, 'jQuery UI': N...",2026-09-14T09:59:57.212703
5,Google LLC,Google LLC,AS396982,34.8.135.182,48012,tcp,NaN,None,US,United States,...,[googleusercontent.com],[182.135.8.34.bc.googleusercontent.com],[],[],NaN,NaN,NaN,NaN,"{'Nginx': None, 'jQuery': None, 'jQuery UI': N...",2026-09-14T10:00:11.237760
6,KPN B.V.,KPN B.V.,AS1136,77.163.107.27,80,tcp,Boa Web Server,None,NL,Netherlands,...,[kpn.net],[77-163-107-27.fixed.kpn.net],"[cpe:/a:jquery:jquery, cpe:/a:jquery:jquery_ui...","[cpe:2.3:a:jquery:jquery, cpe:2.3:a:jquery:jqu...",200.0,Boa/0.94.14rc21,NaN,77.163.107.27,"{'Nginx': None, 'jQuery': {'categories': ['Jav...",2026-09-14T09:59:34.850901
7,Incapsula Inc,Incapsula Inc,AS19551,107.154.135.135,7171,tcp,NaN,None,SG,Singapore,...,[incapdns.net],[107.154.135.135.ip.incapdns.net],[],[],NaN,NaN,NaN,NaN,"{'Nginx': None, 'jQuery': None, 'jQuery UI': N...",2026-09-14T09:59:57.448914
8,Bitly Inc,Google LLC,AS396982,67.199.248.183,12304,tcp,NaN,None,US,United States,...,[],[],[],[],NaN,NaN,NaN,NaN,"{'Nginx': None, 'jQuery': None, 'jQuery UI': N...",2026-09-14T09:59:58.313952
9,"Aliyun Computing Co., LTD","Hangzhou Alibaba Advertising Co.,Ltd.",AS37963,116.62.102.199,44818,tcp,Ingrian SSH,None,CN,China,...,[],[],[],[],NaN,NaN,NaN,NaN,"{'Nginx': None, 'jQuery': None, 'jQuery UI': N...",2026-09-14T09:59:57.602676

In [31]:
con.execute("""
    SELECT COUNT(*) AS total_records
    FROM '../data/processed/observations_test/*.parquet'
""").df()

   total_records
0          10000

In [32]:
con.execute("""
    SELECT
        organization,
        COUNT(*) AS observations
    FROM '../data/processed/observations_test/*.parquet'
    WHERE organization IS NOT NULL
    GROUP BY organization
    ORDER BY observations DESC
    LIMIT 20
""").df()

                 organization  observations
0                  Google LLC          3413
1               Incapsula Inc          2207
2            Amazon.com, Inc.           314
3   Aliyun Computing Co., LTD           297
4            Cloudflare, Inc.           192
5           ACEVILLE PTE.LTD.           170
6                Fly.io, Inc.           152
7              Internet Rimon           122
8    Amazon Technologies Inc.           114
9               Zscaler, Inc.           111
10                  Bitly Inc           105
11    Aliyun Computing Co.LTD           105
12              Korea Telecom            90
13  Akamai Technologies, Inc.            71
14      Fiserv Solutions, LLC            69
15             Incapsula Inc.            67
16      Microsoft Corporation            62
17         Alibaba Cloud - HK            55
18                     Linode            51
19         Alibaba Cloud - SG            42

In [33]:
OBSERVATIONS = (
    PROJECT_ROOT /
    "data" /
    "processed" /
    "observations"
)

print(OBSERVATIONS)

/Users/ishitabelwal/Documents/cybersignal/data/processed/observations

In [34]:
con.execute(f"""
    SELECT COUNT(*) AS total_records
    FROM '{OBSERVATIONS}/*.parquet'
""").df()

   total_records
0        2000000

In [35]:
con.execute(f"""
    SELECT
        COUNT(*) AS observations,
        COUNT(DISTINCT organization) AS organizations,
        COUNT(DISTINCT ip) AS unique_ips,
        COUNT(DISTINCT port) AS unique_ports,
        COUNT(DISTINCT product) AS unique_products,
        COUNT(DISTINCT country_code) AS countries
    FROM '{OBSERVATIONS}/*.parquet'
""").df()

,observations,organizations,unique_ips,unique_ports,unique_products,countries
0,2000000,34065,895550,26435,2035,220

In [ ]:
# Finding the biggest organizations
con.execute(f"""
    SELECT
        organization,
        COUNT(*) AS observation_count,
        COUNT(DISTINCT ip) AS unique_ips,
        COUNT(DISTINCT product) AS unique_products
    FROM '{OBSERVATIONS}/*.parquet'
    WHERE organization IS NOT NULL
    GROUP BY organization
    ORDER BY observation_count DESC
    LIMIT 20
""").df()

                 organization  observation_count  unique_ips  unique_products
0                  Google LLC             667710      248871               76
1               Incapsula Inc             403622       75602               15
2            Cloudflare, Inc.              77211       18772               30
3            Amazon.com, Inc.              71144       29710               90
4   Aliyun Computing Co., LTD              53656       44333              133
5           ACEVILLE PTE.LTD.              29651       22979               26
6    Amazon Technologies Inc.              25505       14335               78
7              Internet Rimon              21401       15663                2
8               Korea Telecom              20646       20537              175
9     Aliyun Computing Co.LTD              17744       15131               97
10          METEVERSE LIMITED              17668        3877                3
11      Microsoft Corporation              16632        9303               80
12         Meteverse Limited.              13397        4290                3
13         Alibaba Cloud - HK              13210        1236                9
14             Incapsula Inc.              12941        2379                1
15               Fly.io, Inc.              12875        8354                2
16                     Linode              12627        1994               98
17  Akamai Technologies, Inc.              12080       10059               16
18        Hetzner Online GmbH               9340        6967              107
19  Amazon Data Services NoVa               8035        5053               52

In [37]:
# Check Countries
con.execute(f"""
    SELECT
        country_code,
        country_name,
        COUNT(*) AS observations,
        COUNT(DISTINCT organization) AS organizations
    FROM '{OBSERVATIONS}/*.parquet'
    GROUP BY country_code, country_name
    ORDER BY observations DESC
    LIMIT 20
""").df()

   country_code        country_name  observations  organizations
0            US       United States       1024896           6381
1            SG           Singapore        416042            381
2            CN               China         99079           1005
3            DE             Germany         52694           3222
4            GB      United Kingdom         40426           1731
5            JP               Japan         34757            924
6            IL              Israel         29256            131
7            HK           Hong Kong         28154            629
8            CA              Canada         27210            853
9            KR  Korea, Republic of         25883            173
10           FR              France         25879           1257
11           NL         Netherlands         18130           1327
12           IN               India         14893            938
13           BR              Brazil         13412           2237
14           IT               Italy          8343           1066
15           ES               Spain          8200            840
16           AU           Australia          7767            515
17           ID           Indonesia          6883            800
18           IE             Ireland          6486            148
19           TW              Taiwan          6286            169

In [38]:
# Check products
con.execute(f"""
    SELECT
        product,
        COUNT(*) AS observations,
        COUNT(DISTINCT organization) AS organizations
    FROM '{OBSERVATIONS}/*.parquet'
    WHERE product IS NOT NULL
      AND TRIM(product) != ''
    GROUP BY product
    ORDER BY observations DESC
    LIMIT 30
""").df()

                                product  observations  organizations
0                                 nginx        105323           6299
1                      CloudFront httpd         40352             46
2                          Apache httpd         35789           5567
3                               AWS ELB         20808             69
4                               OpenSSH         16730           2273
5                           AkamaiGHost         14208            304
6                             OpenResty         11174           1362
7                   Microsoft IIS httpd          9977           2563
8                            CloudFlare          7273            193
9                               Socks4A          5169            128
10                      Ncat http proxy          4054            627
11                  Hikvision IP Camera          3040            862
12              Microsoft HTTPAPI httpd          2974           1105
13                           Chromecast          2830             59
14                                 ntpd          2497           1372
15                         ciscoSystems          2259           1289
16                                  VNC          1692            235
17                             lighttpd          1566            552
18                     Squid http proxy          1373            212
19       MikroTik bandwidth-test server          1373            955
20                        Postfix smtpd          1359            596
21                                BigIP          1340            550
22                              Tengine          1230            125
23                    EZproxy web proxy          1150             63
24              Remote Desktop Protocol          1031            435
25                           Exim smtpd          1022            378
26                             net-snmp          1019            325
27  Microsoft Azure Application Gateway           956             13
28                             MikroTik           909            740
29                                 PPTP           869            566

In [39]:
# Check exposed ports
con.execute(f"""
    SELECT
        port,
        COUNT(*) AS observations,
        COUNT(DISTINCT organization) AS organizations
    FROM '{OBSERVATIONS}/*.parquet'
    WHERE port IS NOT NULL
    GROUP BY port
    ORDER BY observations DESC
    LIMIT 30
""").df()

     port  observations  organizations
0      80        252905          15910
1     443        132127           8116
2    3001         28532            366
3    5503         28374             31
4    1968         28009             29
5    7071         27821            140
6    1337         27807            124
7   14903         26835             37
8    3333         25009            138
9   20000         23781            851
10   5250         23183             34
11   8568         21583             30
12  50112         21095             44
13   2095         20942            105
14   9051         18704            457
15   7547         18655           1277
16   9148         18631            317
17   4343         17629            597
18  62865         17563            275
19   9611         17123            318
20  11180         16915            332
21   9998         16871            139
22   5090         16522           1420
23  37777         16414           1535
24   7082         16204            334
25   5903         15501            398
26   8606         15389            388
27  18113         15140            333
28  44333         14989            332
29   4022         14191            388

In [ ]:
# investigating security-relevant services
#SSH
con.execute(f"""
    SELECT
        organization,
        product,
        port,
        COUNT(*) AS observations
    FROM '{OBSERVATIONS}/*.parquet'
    WHERE
        LOWER(COALESCE(product, '')) LIKE '%ssh%'
        OR port = 22
    GROUP BY organization, product, port
    ORDER BY observations DESC
    LIMIT 30
""").df()

,organization,product,port,observations
0,Google LLC,OpenSSH,22,772
1,"DigitalOcean, LLC",OpenSSH,22,703
2,Hetzner Online GmbH,OpenSSH,22,606
3,Google LLC,NaN,22,344
4,Oracle Corporation,OpenSSH,22,219
5,OVH SAS,OpenSSH,22,172
6,Contabo GmbH,OpenSSH,22,152
7,"Tencent cloud computing (Beijing) Co., Ltd.",OpenSSH,22,149
8,"Vultr Holdings, LLC",OpenSSH,22,136
9,Microsoft Corporation,OpenSSH,22,132
10,Linode,OpenSSH,22,122
11,IONOS SE,OpenSSH,22,111
12,Oracle Public Cloud,OpenSSH,22,108
13,"Tencent Cloud Computing (Beijing) Co., Ltd",OpenSSH,22,107
14,"Asia Pacific Network Information Center, Pty. ...",OpenSSH,22,99
15,EE Limited,OpenSSH,22,87
16,"Aliyun Computing Co., LTD",OpenSSH,1080,86
17,"Aliyun Computing Co., LTD",OpenSSH,10001,84
18,NaN,OpenSSH,22,69
19,Huawei Public Cloud Service (Huawei Software T...,OpenSSH,22,57
20,"NTT America, Inc.",OpenSSH,22,54
21,Unified Layer,OpenSSH,2222,51
22,"OVH Hosting, Inc.",OpenSSH,22,51
23,"Beijing Volcano Engine Technology Co., Ltd.",OpenSSH,22,51
24,Oracle Svenska AB,OpenSSH,22,51
25,ACEVILLE PTE.LTD.,OpenSSH,22,50
26,RackNerd LLC,OpenSSH,22,50
27,Alibaba Cloud (Singapore) Private Limited,OpenSSH,22,47
28,"The Constant Company, LLC",OpenSSH,22,47
29,netcup GmbH,OpenSSH,22,47

In [ ]:
#HTTP
con.execute(f"""
    SELECT
        organization,
        product,
        port,
        COUNT(*) AS observations
    FROM '{OBSERVATIONS}/*.parquet'
    WHERE
        port IN (80, 443)
    GROUP BY organization, product, port
    ORDER BY observations DESC
    LIMIT 30
""").df()

                  organization           product  port  observations
0             Amazon.com, Inc.  CloudFront httpd    80         33106
1             Cloudflare, Inc.               NaN   443         22557
2             Cloudflare, Inc.               NaN    80         21507
3             Amazon.com, Inc.               NaN   443         15226
4    Akamai Technologies, Inc.       AkamaiGHost    80          9093
5             Amazon.com, Inc.  CloudFront httpd   443          6982
6     Amazon Technologies Inc.               NaN    80          5691
7                   Google LLC               NaN    80          5686
8        Microsoft Corporation               NaN    80          5179
9             Cloudflare, Inc.        CloudFlare   443          5102
10    Amazon Technologies Inc.           AWS ELB    80          4681
11                  Google LLC               NaN   443          4633
12    Amazon Technologies Inc.               NaN   443          4621
13            Amazon.com, Inc.               NaN    80          4346
14            Amazon.com, Inc.           AWS ELB    80          3328
15    Amazon Technologies Inc.             nginx    80          2531
16       Microsoft Corporation               NaN   443          2321
17               A100 ROW GmbH           AWS ELB    80          1917
18         Hetzner Online GmbH               NaN    80          1906
19   Amazon Data Services NoVa               NaN    80          1900
20               A100 ROW GmbH               NaN    80          1833
21                      Linode         OpenResty   443          1785
22                      Linode         OpenResty    80          1768
23   Amazon Data Services NoVa           AWS ELB    80          1625
24         Hetzner Online GmbH             nginx    80          1574
25               Korea Telecom               NaN    80          1567
26   Akamai Technologies, Inc.       AkamaiGHost   443          1497
27  Amazon Data Services Japan           AWS ELB    80          1486
28    Amazon Technologies Inc.      Apache httpd    80          1395
29    Amazon Technologies Inc.             nginx   443          1335